[package]
name = "pls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version =  "0.35.4", features = ["dtype-categorical", "dtype-u8", "streaming", "csv", "fmt"]}
